---
couchbase_cluster_namespace: cb-example

ocs_operator_channel: stable
ocs_source_namespace: openshift-marketplace
ocs_source: certified-operators
ocs_spec_name: couchbase-enterprise-certified
couchbase_metadata_name: couchbase-operator-subscription
